### ISSUE TITLE
no rule found for target spnavcfg.o on Linux Mint

### ISSUE THREAD

**Issue by bstabens** [FreeSpacenav/spnavcfg#10] opened 2021-05-08 05:04 UTC
> git clone https://github.com/FreeSpacenav/spnavcfg.git 
...
git-lfs filter-process: 1: git-lfs: not found
git restore --source=HEAD :/
git-lfs filter-process: 1: git-lfs: not found
Connection unexpectedly closed by remote sid.

**Comment by jtsiomb** [comment] 2021-05-08 07:22
The title refers to some kind of build problem, while the message is about some problem with git. Care to elaborate on exactly what this bug report is about? Because at it stands this doesn't make any sense to me.

**Comment by jtsiomb** [comment] 2021-05-08 20:27
I'm closing this bug report. If you find any indication that this is caused by spnavcfg and it's something I need to fix, please re-open and post details.

**Closed by jtsiomb** 2021-05-08 20:27 UTC
